apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "piyush-limits"
spec:
  limits:
  - type: "Pod"
    max:
      cpu: "500m"
      memory: "750Mi"
    min:
      cpu: "10m"
      memory: "5Mi"
  - type: "Container"
    default:
      cpu: "100m"
      memory: "100Mi"
    max:
      cpu: "500m"
      memory: "750Mi"
    min:
      cpu: "10m"
      memory: "5Mi"
  - type: "PersistentVolumeClaim"
    min:
      storage: "2Gi"
    max:
      storage: "10Gi"
